//
//  LoopStorage.swift
//  MusicWaveBoard
//
//  Created by Vitaliy Gribko on 22.10.2021.
//

import Foundation

struct LoopStorage {
    
    static let loopNames = [
        "01": "ICSP006 Background Loop 1",
        "02": "ICSP006 Background Loop 3",
        "03": "ICSP006 Background Loop 4",
        "04": "ICSP006 Clap Loop 1",
        "05": "ICSP006 Clap Loop 4",
        "06": "ICSP006 Clap Loop 5",
        "07": "ICSP006 Clap Loop 8",
        "08": "ICSP006 Drums Loop 11",
        "09": "ICSP006 Drums Loop 14",
        "10": "ICSP006 Drums Loop 15",
        "11": "ICSP006 Drums Loop 16",
        "12": "ICSP006 Drums Loop 17",
        "13": "ICSP006 Glitched Vocal Loop 2",
        "14": "ICSP006 Glitched Vocal Loop 3",
        "15": "ICSP006 Glitched Vocal Loop 8",
        "16": "ICSP006 Groovy Bass Loop 1",
        "17": "ICSP006 Groovy Bass Loop 2",
        "18": "ICSP006 Groovy Bass Loop 4",
        "19": "ICSP006 Groovy Bass Loop 6",
        "20": "ICSP006 Hi Freq Loop 1",
        "21": "ICSP006 Hi Freq Loop 2",
        "22": "ICSP006 Hi Freq Loop 3",
        "23": "ICSP006 Jackin Snare Loop 3",
        "24": "ICSP006 Kick Loop 3",
        "25": "ICSP006 Music Loop 6",
        "26": "ICSP006 Music Loop 7",
        "27": "ICSP006 Music Loop 10",
        "28": "ICSP006 Top Loop 9",
        "29": "ICSP006 Top Loop 10",
        "30": "ICSP006 Top Loop 11",
        "31": "MTR1 bs 127 hypnotic2 E",
        "32": "s2s_dt_126_melo_03 - C#m",
        "33": "s2s_dt_126_melo_13",
        "34": "s2s_dt_126_melo_18 - C#m",
        "35": "s2s_dt_126_melo_39 - G",
        "36": "VMH2 Drumloop 009",
        "37": "VMH2 Drumloop 013",
        "38": "VMH2 Melodyloop 5 Cm 128 Bpm",
        "39": "VMH2 Melodyloop 8 F 128 Bpm",
        "40": "VMH2 Melodyloop 77 C 128 Bpm"
    ]
    
    static let loopTags = [
        "01": ["amazingly", "slow", "echo", "dynamics", "high", "sound", "paced", "trance", "house", "melody", "rhytm"],
        "02": ["beat", "clap","high", "slow"],
        "03": ["beat", "clap", "low", "shake"],
        "04": ["beat", "clap", "low", "slow"],
        "05": ["beat", "slowtempo", "house", "one", "two", "three"],
        "06": ["drums", "fast", "afro", "house", "lounge"],
        "07": ["drums", "fast", "afro", "rhytm"],
        "08": ["drums", "fast", "middle", "afro", "lounge"],
        "09": ["drums", "fast", "rhytm", "trance", "techno", "danceable"],
        "10": ["drums", "high", "upbeat", "metal", "sound", "house"],
        "11": ["drums", "high", "vocal", "afro", "house"],
        "12": ["drums", "low", "rare", "ibiza", "lounge"],
        "13": ["dynamic", "high", "sound", "high", "paced", "trance", "house", "melody", "beats", "danceable"],
        "14": ["dynamic", "high", "sound", "high", "paced", "trance", "house", "melody", "beats", "danceable"],
        "15": ["dynamic", "high", "sound", "high", "paced", "trance", "house", "melody", "beats", "danceable"],
        "16": ["dynamic", "high", "sound", "high", "paced", "trance", "house", "melody", "beats", "danceable"],
        "17": ["dynamic", "high", "sound", "high", "paced", "trance", "house", "melody", "beats", "danceable"],
        "18": ["dynamic", "high", "sound", "middle", "paced", "trance", "house", "melody", "beats", "danceable"],
        "19": ["dynamic", "high", "sound", "super", "slow", "paced", "trance", "house", "melody", "beats", "danceable"],
        "20": ["dynamic", "low", "sound", "slow", "paced", "trance", "house", "melody", "beats", "danceable"],
        "21": ["fantasy", "game", "potion", "bottle", "cork", "pop"],
        "22": ["fas", "metal", "groovy", "energetic"],
        "23": ["fast", "rhytm", "groovy", "bass", "lounge", "beach"],
        "24": ["fast", "speed", "paced", "high", "frequency", "house", "techno", "danceable", "drums", "kick"],
        "25": ["fast", "trance", "house", "groovy", "bass", "techno"],
        "26": ["futuristic", "amazing", "dynamic", "great", "super", "slow", "sound", "los", "paced", "trance", "house", "melody", "danceable"],
        "27": ["futuristic", "dynamic", "great", "high", "sound", "high", "paced", "trance", "house", "melody", "danceable"],
        "28": ["futuristic", "dynamic", "great", "high", "sound", "high", "paced", "trance", "house", "melody", "danceable"],
        "29": ["futuristic", "dynamic", "great", "high", "sound", "high", "paced", "trance", "house", "melody", "melody", "danceable"],
        "30": ["futuristic", "dynamic", "great", "high", "sound", "middle", "paced", "trance", "house", "melody", "melody", "danceable"],
        "31": ["futuristic", "dynamic", "great", "high", "sound", "slow", "paced", "trance", "house", "melody", "danceable"],
        "32": ["futuristic", "dynamic", "great", "high", "sound", "slow", "paced", "trance", "house", "melody", "danceable"],
        "33": ["futuristic", "dynamic", "great", "high", "sound", "slow", "paced", "trance", "house", "danceable"],
        "34": ["futuristic", "dynamic", "great", "low", "sound", "slow", "paced", "trance", "house", "melody", "danceable"],
        "35": ["futuristic", "dynamic", "great", "low", "sound", "super", "slow", "paced", "trance", "house", "melody", "danceable"],
        "36": ["groovy", "bass", "jazz", "fast"],
        "37": ["high", "dynamics", "high", "paced", "fast", "house", "techno", "danceable", "trance", "melody", "rhytm"],
        "38": ["high", "dynamics", "high", "sound", "high", "paced", "fast", "house", "lounge", "danceable", "trance", "melody", "rhytm"],
        "39": ["high", "dynamics", "high", "sound", "high", "paced", "fast", "house", "lounge", "danceable", "trance", "melody", "rhytm"],
        "40": ["high", "dynamics", "high", "sound", "high", "paced", "trance", "house", "melody", "rhytm"],
        "41": ["high", "dynamics", "low", "sound", "high", "paced", "fast", "house", "lounge", "danceable", "trance", "melody", "rhytm"],
        "42": ["high", "dynamics", "low", "sound", "high", "paced", "fast", "house", "techno", "danceable", "trance", "melody", "rhytm "],
        "43": ["high", "dynamics", "low", "sound", "high", "paced", "fast", "house", "techno", "danceable", "trance", "melody", "rhytm"],
        "44": ["high", "fast", "dynamics", "high", "sound", "fast", "high", "syynthetic", "paced", "trance", "house", "melody", "rhytm"],
        "45": ["high", "speed", "low", "Kick", "drum", "house", "techno", "danceable"],
        "46": ["high", "speed", "low", "sound", "kick", "drum", "house", "techno", "danceable"],
        "47": ["high", "tempo", "drum", "techno", "metal", "percusisve", "danceable"],
        "48": ["lounge", "groovy", "bass", "slow"],
        "49": ["low", "dynamics", "high", "sound", "low", "paced", "trance", "house", "melody", "rhytm"],
        "50": ["low", "dynamics", "high", "sound", "low", "paced", "trance", "house", "melody", "rhytm"],
        "51": ["low", "dynamics", "high", "sound", "low", "paced", "trance", "house", "melody", "rhytm"],
        "52": ["low", "groovy", "bass", "fast"],
        "53": ["low", "groovy", "bass", "slow"],
        "54": ["low", "speed", "slow", "paced", "echo", "techno", "trance", "melody"],
        "55": ["male", "vocal", "fast", "high", "house"],
        "56": ["melody", "loop", "high", "start", "trance", "house"],
        "57": ["melody", "loop", "slow", "start", "trance", "house"],
        "58": ["middle", "paced", "beat", "dynamics", "middle", "sound", "slow", "paced", "trance", "house", "melody", "rhytm"],
        "59": ["middle", "paced", "house", "techno", "danceable", "trance", "melody", "rhytm", "melodic"],
        "60": ["middle", "paced", "house", "techno", "danceable", "trance", "melody", "rhytm"],
        "61": ["rhytm", "fast", "groovy", "bass", "house", "techno", "trance"],
        "62": ["rhytm", "fast", "groovy", "bass", "house"],
        "63": ["slow", "paced", "guitar", "melody", "jazz", "house"],
        "64": ["slow", "paced", "house", "techno", "danceable", "trance", "melody", "rhytm"],
        "65": ["speed", "paced", "high", "frequency", "house", "techno", "danceable", "drums"],
        "66": ["speed", "paced", "high", "frequency", "house", "techno", "danceable", "start"],
        "67": ["speed", "paced", "high", "tempo", "low", "sound", "house", "techno", "danceable", "drums"],
        "68": ["speed", "paced", "slow", "tempo", "house", "techno", "danceable", "real", "drums"],
        "69": ["super", "high", "dynamics", "high", "sound", "super", "high", "paced", "trance", "house", "melody", "rhytm"],
        "70": ["super", "low", "dynamics", "high", "sound", "low", "paced", "trance", "house", "melody", "rhytm"],
        "71": ["super", "low", "dynamics", "high", "sound", "super", "low", "paced", "trance", "house", "melody", "rhytm"],
        "72": ["super", "slow", "echo", "dynamics", "high", "sound", "super", "slow", "paced", "trance", "house", "melody", "rhytm"],
        "73": ["super", "slow", "echo", "dynamics", "high", "sound", "super", "slow", "paced", "trance", "house", "melody", "rhytm"],
        "74": ["super", "slow", "echo", "dynamics", "high", "sound", "super", "slow", "paced", "trance", "house", "melody", "rhytm"],
        "75": ["super", "slow", "echo", "dynamics", "high", "sound", "super", "slow", "paced", "trance", "house", "melody", "rhytm"],
        "76": ["very", "fast", "rhytm", "groovy", "bass", "high", "tempo"],
        "77": ["vocal", "glitched", "afro", "woman"],
        "78": ["woman", "vocal", "lound", "house", "high"]
    ]
}
